networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev

  backend:
    build:
      context: ./backend_library
    networks:
      - dev
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend_library
    depends_on:
      - backend
    networks:
      - dev
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1/
    expose:
      - "3000"