networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - '/etc/nginx/certs:/etc/nginx/certs'
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './backend_library/media:/opt/media'
    networks:
      - dev

  backend:
    build:
      context: ./backend_library
    networks:
      - dev


  frontend:
    build:
      context: ./frontend_library
    networks:
      - dev