networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev

  backend:
    env_file:
      - back.env
    build:
      context: ./backend_library
    networks:
      - dev

  frontend:
    env_file:
      - web.env
    build:
      context: ./frontend_library
    networks:
      - dev